### ISSUE TITLE
Change dependent versioning to semantic versioning using the compatible release specifier

### ISSUE THREAD

**Issue by paulf81** [NREL/wind-hybrid-open-controller#3]
Improve dependencies to use compatible release specifier such that the dependencies won't go up a major version unless intentionally changed in an update to this repo. This is to avoid breaks due to API changes. Info on compatible release specifier:

https://packaging.python.org/en/latest/specifications/version-specifiers/#id4

**Comment by misi9170** [comment]
I believe this is suitably addressed in #41 . The exception is `zmq`, but that isn't really needed currently and we can provide a semantic version when we address issues #4 , #6
